INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (100, 1, 4, "success");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (34.7, 2, 3, "success");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (12.4, 12, 5, "success");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (22.3, 17, 2, "success");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (5.3, 4, 8, "success");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (11.5, 5, 2, "failure");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (6.6, 6, 10, "success");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (2.33, 24, 11, "failure");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (91.3, 7, 17, "success");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (22, 18, 4, "in progress");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (5, 9, 1, "success");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (12, 2, 21, "success");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (10, 14, 26, "in progress");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (45.2, 16, 7, "failure");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (34, 10, 25, "success");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (6, 2, 8, "success");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (7.5, 5, 23, "failure");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (22.2, 4, 13, "failure");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (12, 5, 45, "success");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (2, 11, 77, "failure");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (100, 20, 55, "success");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (31.2, 19, 3, "in progress");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (30, 2, 14, "failure");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (17.5, 17, 15, "success");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (34.2, 45, 23, "failure");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (13, 15, 1, "in progress");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (14, 15, 3, "failure");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (23, 15, 25, "in progress");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (55, 15, 11, "success");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (24, 15, 11, "failure");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (10.2, 15, 11, "failure");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (43, 5, 11, "failure");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (29, 5, 17, "failure");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (77, 5, 17, "success");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (14.5, 18, 11, "in progress");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (25, 18, 11, "in progress");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (44, 18, 17, "in progress");
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`, `status`) VALUES (19, 18, 11, "failure");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (108.72, 22, 41, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (144.26, 18, 20, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (191.85, 30, 83, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (93.04, 16, 74, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (46.03, 3, 107, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (160.83, 22, 53, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (199.53, 14, 18, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (25.61, 5, 45, "failure");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (195.65, 23, 17, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (185.77, 22, 37, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (44.22, 12, 59, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (130.02, 17, 28, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (14.23, 5, 40, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (125.87, 3, 6, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (16.65, 14, 45, "failure");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (98.52, 3, 12, "failure");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (116.53, 23, 51, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (8.33, 12, 102, "in progress");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (164.12, 29, 12, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (143.44, 24, 14, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (11.68, 23, 35, "in progress");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (65.64, 23, 36, "in progress");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (51.78, 4, 30, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (54.53, 18, 11, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (187.82, 10, 39, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (106.89, 26, 100, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (19.56, 2, 48, "in progress");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (142.47, 3, 17, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (24.80, 30, 100, "failure");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (93.63, 3, 73, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (147.92, 7, 87, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (116.13, 16, 96, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (185.39, 20, 97, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (61.84, 4, 72, "in progress");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (76.84, 23, 12, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (139.19, 30, 26, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (150.36, 4, 23, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (43.09, 2, 41, "failure");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (170.15, 10, 101, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (11.55, 25, 99, "failure");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (64.30, 5, 61, "failure");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (82.71, 25, 99, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (43.13, 4, 102, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (2.09, 4, 37, "in progress");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (16.50, 5, 12, "failure");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (95.23, 20, 72, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (47.86, 22, 63, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (45.90, 11, 82, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (139.62, 26, 105, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (188.01, 8, 63, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (113.41, 20, 7, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (184.73, 13, 26, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (119.27, 2, 86, "in progress");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (165.29, 12, 101, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (69.15, 9, 82, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (112.02, 15, 19, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (186.28, 21, 71, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (124.65, 12, 41, "in progress");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (173.44, 19, 96, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (129.12, 29, 27, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (119.98, 8, 9, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (87.97, 25, 9, "failure");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (39.52, 15, 50, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (189.47, 21, 38, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (52.52, 25, 55, "in progress");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (27.77, 12, 27, "failure");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (121.66, 17, 41, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (163.49, 3, 46, "in progress");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (28.28, 20, 20, "in progress");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (96.32, 19, 33, "in progress");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (70.54, 8, 22, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (169.13, 11, 67, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (22.48, 1, 11, "failure");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (161.65, 17, 75, "in progress");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (17.92, 28, 41, "failure");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (24.98, 30, 84, "in progress");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (44.32, 2, 13, "in progress");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (164.32, 6, 77, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (150.37, 7, 14, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (147.41, 5, 30, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (179.25, 22, 35, "in progress");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (13.90, 3, 83, "in progress");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (164.64, 29, 90, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (194.27, 2, 34, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (174.34, 7, 32, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (91.80, 28, 77, "in progress");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (80.64, 12, 13, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (133.87, 24, 60, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (29.19, 16, 30, "failure");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (171.64, 25, 95, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (9.66, 17, 55, "failure");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (147.74, 7, 88, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (55.71, 10, 9, "in progress");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (38.23, 8, 88, "failure");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (176.91, 20, 44, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (110.18, 27, 106, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (168.56, 28, 91, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (176.38, 28, 87, "success");
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id', `status`) VALUES (49.41, 24, 88, "failure");
