INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (100, 1, 4);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (34.7, 2, 3);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (12.4, 12, 5);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (22.3, 17, 2);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (5.3, 4, 8);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (11.5, 5, 2);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (6.6, 6, 10);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (2.33, 24, 11);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (91.3, 7, 17);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (22, 18, 4);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (5, 9, 1);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (12, 2, 21);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (10, 14, 26);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (45.2, 16, 7);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (34, 10, 25);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (6, 2, 8);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (7.5, 5, 23);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (22.2, 4, 13);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (12, 5, 45);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (2, 11, 77);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (100, 20, 55);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (31.2, 19, 3);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (30, 2, 14);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (17.5, 17, 15);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (34.2, 45, 23);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (13, 15, 1);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (14, 15, 3);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (23, 15, 25);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (55, 15, 11);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (24, 15, 11);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (10.2, 15, 11);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (43, 5, 11);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (29, 5, 17);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (77, 5, 17);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (14.5, 18, 11);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (25, 18, 11);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (44, 18, 17);
INSERT INTO `bid_log`(`bid_amt`, `user_id`, `stuff_id`) VALUES (19, 18, 11);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (108.72, 22, 41);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (144.26, 18, 20);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (191.85, 30, 83);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (93.04, 16, 74);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (46.03, 3, 107);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (160.83, 22, 53);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (199.53, 14, 18);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (25.61, 5, 45);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (195.65, 23, 17);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (185.77, 22, 37);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (44.22, 12, 59);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (130.02, 17, 28);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (14.23, 5, 40);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (125.87, 3, 6);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (16.65, 14, 45);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (98.52, 3, 12);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (116.53, 23, 51);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (8.33, 12, 102);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (164.12, 29, 12);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (143.44, 24, 14);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (11.68, 23, 35);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (65.64, 23, 36);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (51.78, 4, 30);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (54.53, 18, 11);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (187.82, 10, 39);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (106.89, 26, 100);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (19.56, 2, 48);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (142.47, 3, 17);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (24.80, 30, 100);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (93.63, 3, 73);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (147.92, 7, 87);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (116.13, 16, 96);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (185.39, 20, 97);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (61.84, 4, 72);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (76.84, 23, 12);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (139.19, 30, 26);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (150.36, 4, 23);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (43.09, 2, 41);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (170.15, 10, 101);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (11.55, 25, 99);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (64.30, 5, 61);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (82.71, 25, 99);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (43.13, 4, 102);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (59.12, 22, 78);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (2.09, 4, 37);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (16.50, 5, 12);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (95.23, 20, 72);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (47.86, 22, 63);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (45.90, 11, 82);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (139.62, 26, 105);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (188.01, 8, 63);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (113.41, 20, 7);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (184.73, 13, 26);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (119.27, 2, 86);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (165.29, 12, 101);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (69.15, 9, 82);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (112.02, 15, 19);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (186.28, 21, 71);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (124.65, 12, 41);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (173.44, 19, 96);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (129.12, 29, 27);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (119.98, 8, 9);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (87.97, 25, 9);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (39.52, 15, 50);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (189.47, 21, 38);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (52.52, 25, 55);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (27.77, 12, 27);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (121.66, 17, 41);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (163.49, 3, 46);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (28.28, 20, 20);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (96.32, 19, 33);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (70.54, 8, 22);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (169.13, 11, 67);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (22.48, 1, 11);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (161.65, 17, 75);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (17.92, 28, 41);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (24.98, 30, 84);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (44.32, 2, 13);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (164.32, 6, 77);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (150.37, 7, 14);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (147.41, 5, 30);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (179.25, 22, 35);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (13.90, 3, 83);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (164.64, 29, 90);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (194.27, 2, 34);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (174.34, 7, 32);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (91.80, 28, 77);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (80.64, 12, 13);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (133.87, 24, 60);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (29.19, 16, 30);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (171.64, 25, 95);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (9.66, 17, 55);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (147.74, 7, 88);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (55.71, 10, 9);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (38.23, 8, 88);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (176.91, 20, 44);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (110.18, 27, 106);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (168.56, 28, 91);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (176.38, 28, 87);
INSERT INTO `bid_log` ('bid_amt', 'user_id', 'stuff_id') VALUES (49.41, 24, 88);
